### ISSUE TITLE
"Install Simulation Models" dialog does not use proxy server for web access

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#1037]
**Platform**
 - OMNeT++ version: 6.0.1
 - OS: Windows 11, but likely all OSes

**Describe the bug**
If the web can only be accessed via a proxy, bringing up the *Help -> Install Simulation Models...* dialog in the IDE will result in an error dialog, strangely saying "Invalid thread access". The IDE does not pick up the system's proxy settings.

**Solution / Workaround**

As it turns out, the standard Java HTTP client library (which the code uses) is able to detect and use proxies, but this feature is turned off by default. It has to be instructed to do so via system property: by setting java.net.useSystemProxies=true; or if that doesn't work, by setting https.proxyHost and https.proxyPort, etc.  See Java documentation, https://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html

These system properties can be set in the Eclipse ini file which contains JVM args. In the OMNeT++ installation, edit "ide/opp_ide.ini", and append the following line:

-Djava.net.useSystemProxies=true

or other related properties.

In future OMNeT++ releases, java.net.useSystemProxies should probably be turned on by default.

**Comment by avarga** [comment]
The same happens if there is no internet connection (or communication breaks for any other reason).

A dialog box should be displayed with the _appropriate_ error message (not "invalid thread access"), **and additionally**, with a hint on host to access Eclipse's _Network Communication_ preference page.

**Comment by torokati44** [comment]
> Eclipse has a proxy configuration page, Window -> Preferences -> General -> Network Connection.
> Thus, the use of system properties java.net.useSystemProxies=true, etc, is probably unnecessary.

The "Native" provider option in that dialog reads the system configuration, regardless of this property.
 - On Linux, it reads from gsettings where available (that is, on GNOME and its relatives); otherwise, reads the `http_proxy`, `https_proxy`, and `socks_proxy` environment variables.
 See: https://git.eclipse.org/c/platform/eclipse.platform.team.git/tree/bundles/org.eclipse.core.net.linux/src/org/eclipse/core/net/ProxyProvider.java
 - On Windows, it reads the IE proxy setting using the WinHTTP library. (https://learn.microsoft.com/en-us/windows/win32/winhttp/about-winhttp)
 See: https://git.eclipse.org/c/platform/eclipse.platform.team.git/tree/bundles/org.eclipse.core.net.win32/src/org/eclipse/core/net/ProxyProvider.java
 
 The "Direct" provider means no proxy, and the "Manual" provider is (of course) for manual proxy configuration.
