### ISSUE TITLE
Formatting plot axis units

### ISSUE THREAD

**Issue by msdlr** [omnetpp/omnetpp#1247]
Hello, 
This issue is not specific to any particular version of omnetpp. I use the IDE to plot values for statistics on an omnet(6.0.0 onwards)-based simulator and several or the statistic I work with are recorded as simtime_t. Results for them in .sca files are doubles, as one would expect. However, when dealing with sub-microsecond values, we might want to convert the values from seconds to microseconds instead. And having the exponent on the axis is an eyesore really, more so when the exponent is not a multiple of 3.

A way for me to do it would be to change the python script for plots, but that would involve messing with the dataframe right before plotting. Would it be possible to have the option for engineering formatting on the axes of plots? Matplotlib is already shipping this feature and it would be neat to have this on the plot properties windows.
I guess we could record more than one statistic for the same signal and apply a filter, but the issue is with representation really, not the values themselves.
Thanks in advance!

**Comment by torokati44** [comment]
Hello,

I assume you're using Matplotlib-based charts within the IDE, as the "native" plot widgets don't extract a separate common scale exponent of the axis tick labels.

I assume (again :D) that by "matplotlib already shipping this", you mean this here: https://matplotlib.org/stable/api/ticker_api.html#matplotlib.ticker.EngFormatter
 
This looks very nice, and had it been out already when OMNeT++ 6.0 came out, we definitely would have made use of it. It was just a few months too late!

We want to do some proper unit handling and user-friendly conversions in the charts as well, and this feature of Matplotlib will make it a lot easier. But maybe we'll hook up our own "tried and tested" custom unit conversion handling - that is already used in many other places - here as well.

Until then, you can disable the exponent extraction functionality of Matplotlib by adding these lines to the "Advanced" tab of the properties dialog of your charts:

```
axes.formatter.limits : -30, 30
axes.formatter.useoffset: False
```

These are so-called `rcParams`, documented here: https://matplotlib.org/stable/api/matplotlib_configuration_api.html#matplotlib.rcParams

And to enable this engineering formatter, you could add this snippet to the chart script itself, without having to touch the DataFrame or the values in it in any way.

```python
import matplotlib.pyplot as plt
from matplotlib.ticker import EngFormatter
                               
ax = plt.gca()

# With appropriate units for each axis of course
ax.xaxis.set_minor_formatter(EngFormatter('s'))
ax.xaxis.set_major_formatter(EngFormatter('s'))
ax.yaxis.set_minor_formatter(EngFormatter('s'))
ax.yaxis.set_major_formatter(EngFormatter('s'))
```

Make sure to add this *after* the line

```python
utils.postconfigure_plot(props)
```

otherwise this would undo it.

Finally, you might want to set a manual axis label, to remove the automatically appended unit in square brackets, which could be confusing this way.


Additionally, the `convert_to_base_unit` argument of many result querying functions in the `omnetpp.scave.results` Python module (usually one called by the script of every provided chart template) might be relevant here - although it doesn't affect the time axis of vectors IIRC.

**Comment by msdlr** [comment]
You just nailed it, thanks a lot!
![imagen](https://github.com/user-attachments/assets/af0d697f-fa96-467c-a25d-80a9873d05e7)
