### ISSUE TITLE
OMNeT++ 6.1 matplotlib verison too old, but the version upgrade unsuccessful

### ISSUE THREAD

**Issue by ChenVadder** [omnetpp/omnetpp#1293]
**Platform**
 - OMNeT++ version: [e.g. 6.1]
 - OS: [e.g. win64]

**Describe the bug**
titoc samples, txc15, results analysis:
WARNING: 'matplotlib' is too old, some analysis tool functionality may be broken. Required: 3.5.3, present: 3.5.2. Try running `python3 -m pip install --user --upgrade matplotlib` to upgrade.

But, when run "python3 -m pip install --user --upgrade matplotlib" in Terminal(Ctrl + Shift + Alt +T),  will get:
"""
Requirement already satisfied: matplotlib in d:/software/omnetpp-6.1/tools/win32.x86_64/mingw64/lib/python3.10/site-packages (3.5.2)
Collecting matplotlib  Using cached matplotlib-3.10.0.tar.gz (36.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
……
……
……
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.hint: See above for details.
"""

**To Reproduce**
titoc samples, txc15, run and try results analysis

Thinks!

**Comment by rhornig** [comment]
Ignore the warning. The 3.5.2 version that comes with the widows installation has a rendering issue, but that was 'hot patched' in the release, so it actually does NOT have the problem. You cannot upgrade the matplotlib library because the matplotlib packages are installed by the msys pacman package manager (i.e. they are installed by an external package manager and NOT by PIP)

Log story short... Ignore the wrning.
