### ISSUE TITLE
getReferecedProjects() may return collection that contain nulls

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#422]
**Reported by rhornig on 11 Apr 2012 15:19**

**Version:** 4.2.2

This can happen if the referenced project does not exist at all.

See MakeMake.java:544
            for (IProject project : folder.getProject().getReferencedProjects()) { //XXX should use transitive closure o
                if (project.getLocation().isPrefixOf(location)) {                                                       
                    containingProject = project; break;                                                                 
                }                                               

[Mantis Bugtracker #559](https://dev.omnetpp.org/bugs/view.php?id=559)

**Comment by avarga** [comment]
As of 6.0, that particular instance of `getReferencedProjects` is no longer present in the code, but there are ~10 others.

**Comment by avarga** [comment]
Closing as there is no evidence that the issue still exists. It was reported against an old Eclipse version, and the result of null elements in the return value of `getReferencedProjects` was probably an Eclipse bug that was fixed since then. The method's doc explicitly says "The returned projects need not exist in the workspace.", i.e. nonexisting or closed projects won't appear in the result as nulls.
