### ISSUE TITLE
File search: clicking on result opens NED files in text editor

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#634]
**Reported by woife on 2 Oct 2015 10:43**

**Version:** 5.0b1

When doing a file search, and the search results contain all files that contain the searched text. This view can be expanded to show every single line that was found.

Clicking on a line should open the file in the corresponding editor, but for NED files this does not work. Clicking on lines of NED files opens the default text editor. Clicking on the file itself correctly opens the NED editor.

**Steps to reproduce:** * Open a file search (from the menu: File-&gt;Search)
* Search for some text that is contained in a NED file
* The results will show this file, and you can expand the view to also show the lines that match your search request
* Double click on the file name in the search results --&gt; the NED file opens in the NED editor (expected)
* Double click on a line in the search results --&gt; the NED opens in the default text editor, thus it has no syntax highlighting, etc.

**Additional information:** The attached PNG file shows a screenshot with remarks what happens when clicking on different result entries.
![filesearchned](https://user-images.githubusercontent.com/40529/49439096-7005a600-f7c0-11e8-87bf-ce06b5a0e847.png)

[Mantis Bugtracker #836](https://dev.omnetpp.org/bugs/view.php?id=836)

**Comment by avarga** [comment]
The problem seems to be that the NED editor is opened via a launcher class. The relevant code inside Eclipse:

`EditorOpener` class:
```
	public IEditorPart openAndSelect(IWorkbenchPage wbPage, IFile file, int offset, int length, boolean activate) throws PartInitException {
		String editorId= null;
		IEditorDescriptor desc = IDE.getEditorDescriptor(file, true, true);
		if (desc == null || !desc.isInternal()) {    <--------- isInternal() returns false for the NED editor
			editorId= "org.eclipse.ui.DefaultTextEditor"; //$NON-NLS-1$  <------------- so the plain text editor is chosen
		} else {
			editorId= desc.getId();
		}
		(code proceeds to open the editor whose type is in editorId)
```
where:

```
	public boolean isInternal() {
		return getOpenMode() == OPEN_INTERNAL;
	}
```

and:

```
	private int getOpenMode() {
		if (configurationElement == null) { // if we've been serialized, return our serialized value
			return openMode;
		} else if (getLauncher() != null) {   <----------- NED editor is registered as a launcher
			// open using a launcher
			return EditorDescriptor.OPEN_EXTERNAL;
		...
```

**Comment by avarga** [comment]
There is a good reason NED Editor is started via a launcher class: the NED Editor (currently) cannot open NED files that are outside NED folders. Therefore, when the user wants to open such a NED file, we open it in a plain text editor instead. However, choosing whether to open a NED Editor or a plain text editor is only possible inside a launcher class. (It is not possible for an editor being opened to say "I cannot handle this file, please dispose me and open this other type of editor instead.")

The only way of resolving this issue seems to be to make the NED editor accept NED files outside NED folders. However, doing so likely requires extensive changes.
