### ISSUE TITLE
CFLAGS='-DXXX -DYYY' ./configure fails

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#703]
**Reported by sommer on 4 May 2017 14:19**

**Version:** 5.1

running a command like...

CFLAGS=&#039;-DXXX -DYYY&#039; ./configure

...seems to trigger a parser error (space in list of parameters) of the configure script.

**Additional information:** The ./configure run outputs:

./configure: eval: line 2216: unexpected EOF while looking for matching `&#039;&#039;

(exit 2)

[Mantis Bugtracker #1006](https://dev.omnetpp.org/bugs/view.php?id=1006)

**Comment by danieldjewell** [comment]
I just ran into the same issue ... In my case, `$CFLAGS` and `$CXXFLAGS` are both set in my bash/zsh profile as defaults.

Running `unset CFLAGS CXXFLAGS` fixed the issue. This was quite surprising to me since Autoconf/Automake/Autotools-based builds typically handle these environment variables without issue... 

@sommer @rhornig Perhaps this might want to be reclassified into a higher priority item?
