### ISSUE TITLE
The IDE freezes and runs out of memory while indexing INET C++ code

### ISSUE THREAD

**Issue by tim-ist** [omnetpp/omnetpp#754]
**Platform**
 - OMNeT++ version: 5.4.1
 - OS: Mac OS 10.14.3 (Mojave)

**Describe the bug**
While indexing C/C++ the IDE freezes on a cc file, consumes all CPU cycles and system memory, and crashes.

**To Reproduce**
Import the INET project (in my case version 4.1.0). Run the C/C++ indexer (Project->C/C++ Index->Rebuild).

![omnet_indexer_bug_2](https://user-images.githubusercontent.com/1457772/52782720-0a4f5900-3050-11e9-99f6-8b39fb281a0f.png)
![omnet_indexer_bug](https://user-images.githubusercontent.com/1457772/52782721-0a4f5900-3050-11e9-8402-4e0aa742a86d.png)

**Comment by weinrank** [comment]
Same here!

Tested with `OMNeT++ 5.4.1 `and `OMNeT++ 6.0 - Preview 2` on `Linux` and `Mac OS`.

And it always hangs at the same point : `.../ieee80211/mac/blockack`

![image](https://user-images.githubusercontent.com/6726222/54424568-7981a100-4713-11e9-859e-949fb092b2d9.png)

**Comment by tim-ist** [comment]
Indeed, it always hangs on ```OriginatorBlockAckAgreementHandler.cc``` . Also with a fresh snapshot of INET (```627ada8c65f0294561e68f4cfe1260b039d46a87```)

**Comment by danielsengkey** [comment]
I recently pull the fresh snapshot of INET this morning (commit 628010a78b2ca7de67b2024cbd1900d374a02ed9) and experienced this problem. The last commit of INET I tried prior to this one (around December last year), did not have this problem. I tried to increase the heap size of OMNeT++ to no avail.
![2019-04-15-122843_1920x1080_scrot](https://user-images.githubusercontent.com/10163132/56107771-ba6f0e80-5f7a-11e9-817a-3c6cea3f212f.png)

**Comment by ign0tus** [comment]
I have the same problem.
Arch Linux, 16GB of RAM
openjdk version "1.8.0_212"
OMNET++ 5.4.1; INET 4.1.0

Is it possible to disable indexing at all?

**Comment by avarga** [comment]
We suffer from this problem in-house as well, it is indeed very annoying, we are currently exploring it. It seems to be an indexer scalability issue, i.e. not a bug. We'll post here if/when we find a solution.

**Comment by rhornig** [comment]
Ok, just to keep you updated. This is definitely a bug in the CDT indexer which surfacing as a scalability issue. I'm trying to narrow down this and report to the CDT developers. This bug seems to be present for ages in CDT, it's just the INET 4.0 codebase triggered it to be surfaced. It seems that the new packet API with lots of descendants from Chunk class is causing the issue. We will try to get it fixed, however this depends on CDT developers.

**Comment by rhornig** [comment]
Ok here it is: It seems that the issue is indeed in CDT. If a header file does not start directly with e header guard ifdef, CDT Indexer pareses it several times triggering the above issue. Although this is a bug in CDT, if we modify OMNeT++ message compiler to always generate the hedear guard as the first non-comment line, this issue is not triggered. You should apply the patch below on top of OMNeT++ 5.4.1 (or later).

https://github.com/omnetpp/omnetpp/commit/e182b011b0fe377e6269889ffddea513fa2fdb1c
