### ISSUE TITLE
Obsolete parameter data in result files

### ISSUE THREAD

**Issue by mbyrenh** [omnetpp/omnetpp#757]
If a named configuration overwrites a module parameter that was previously specified in the [General]-section of the ini file, then both values are written into the sca, vec and vci file.

For example, if the ini file contains the following content:
```
[General]
**.MyModule.MyParam = ""

[Config myConfig]
**.MyModule.MyParam = "myValue"
```

then the resulting sca/vec/vci-file will contain the lines

```
param **.MyModule.MyParam = "\"myValue\""
param **.MyModule.MyParam = "\"\""
```
In my case, I can not use the R-package for OMNet on the resulting sca-files, as the loadDataset-call would crash with the error 
```
Error in callLoadDataset: Value of module parameter conflicts with previously loaded value
```
I have multiple named configurations where in most of them, I do not change the parameter already given in the General-section. If this is bad style, it might be helpful if OMNet would complain at the start of the simulation.

**Comment by avarga** [comment]
Probably reported against OMNeT++ 5.x. For that version, the documented behavior is the correct one, as `param` entries are just copies of the parameter assignment lines in the ini file. As the same parameter can be matched by several different wildcard patterns (and the first one wins), no attempt is made to filter out apparent duplicates, not even filtering out exact duplicates. Also note that the values may contain expressions like `exponential(3.1)`, from which the actual runtime values cannot be deduced.

As of OMNeT++ 6.0, this bug is obsolete, as the file format has changed. `config` lines contain the copies of the assignment (and other configuration) lines from the ini file, and this should be more intuitive. To get the values of parameters, read the `par` lines that record the actual values. 

See a sample fragment of a 6.x result file:

```
config Aloha.txRate 9.6kbps
config Aloha.host[*].pkLenBits 952b
config **.x "uniform(0m, 1000m)"   <--- NOTE: stochastic expression!
config **.y "uniform(0m, 1000m)"
config **.animationHoldTimeOnCollision 0s
config **.idleAnimationSpeed 1

par Aloha.server typename "\"Server\""
par Aloha.server x 548.814m     <--- Note: concrete value, the result of the evaluating the expression
attr unit m
par Aloha.server y 592.845m
attr unit m
par Aloha.server animationHoldTimeOnCollision 0s
attr unit s
```
