### ISSUE TITLE
[help needed] Understanding use of  `setAssociatedObject` in aloha

### ISSUE THREAD

**Issue by mmodenesi** [omnetpp/omnetpp#777]
**Platform**
 - OMNeT++ version: 5.1.1
 - OS: irrelevant

I am studying the provided samples as a way to gain insight about what I can do with OMNeT++. In `aloha` simulation I see the in the code for the hosts:

```c++
        // let visualization code know about the new packet
        if (transmissionRing != nullptr) {
            delete lastPacket;
            lastPacket = pk->dup();
        }
```

Context: the method is `handleMessage`. The host is `IDLE` and receives a self message intended to wake it up and start next transmission. `lastPacket` is a pointer to the last `cPacket` sent to the server. `transmissionRing` "knows" about the `lastPacket` because of a previous call to `transmissionPacket->setAssociatedObject(lastPacket)`.

#### Please help me understand this:

Doesn't this leave a dangling pointer inside the `transmissionRing`?

Quoting the docs, _the user is responsible for ensuring that the pointer is valid (the corresponding object exists), and remains valid while it is associated with the figure._

The next call to `transmissionPacket->setAssociatedObject(lastPacket)` will occur very soon, on the next invocation of `refreshDisplay`, so the time the dangling pointer is held by the `cRingFigure` is small, I know. But since this is an "educational" kind of sample, shouldn't it set the associated object of the figure (as well as all the transmission circles) to `nullptr`?

Thanks for your attention!

**Comment by torokati44** [comment]
I think, technically you are right. The dangling pointer to the old and deleted packet is indeed kept in the figure for some time.
However, the associated object field of the figures are intended to be a "one-way channel" from the model through the envir to the user. So ideally it should not used read by the model

**Comment by torokati44** [comment]
I think, technically you are right. The dangling pointer to the old and deleted packet is indeed kept in the figure for some time - until `refreshDisplay()` is called.
However, the `associatedObject` field of the figures is intended to be a "one-way channel" from the model through the envir to the user. So ideally it should not used by the model. It's fine to read the pointer itself (it is in fact done in the aloha sample as well), but if the model doesn't ensure that it is always valid, it shouldn't be dereferenced.
And I don't think this is a problem, since the envir should make sure (unless it is buggy) that `refreshDisplay()` is called "often enough", and "whenever necessary" - between executing any event, and letting the user interact with the model in any way. So, updating the `associatedObject` field in `handleMessage()` is not necessary.
In fact, the whole point of adding the `refreshDisplay()` function was to decouple the code that communicates info to the user from the parts that are essential for the model's operation. This hopefully improves code quality and runtime performance, by slightly reducing the unnecessary visualization-related processing overhead for every single event.

**Comment by mmodenesi** [comment]
Thanks for the explanation! I understand what you say and why it "doesn't matter" in this case.

The only point that still makes me doubt, though, is that as a user, I do not know (nor should know, for that matters) how will `cFigure` or the current `Envir` make use of the pointer I pass through `setAssociatedObject`. I'd feel more confortable setting the associated object to `nullptr` (or to the new `cPacket) and rest assured that no dangling pointer is haunting.

I accidentally came across this detail working on the python bindings for `cSimpleModule`. It turns out that `if self.transmissionRing.getAsssocatedObject() is None:` in the python version of `refreshDisplay` does indeed dereference the (sometimes dangling) pointer, as python woldn't just return a memory address, but a complete object.

**Comment by torokati44** [comment]
Oh, nice find then!

**Comment by torokati44** [comment]
I understand your doubts. But the `associatedObject` field _is_ in fact updated to the new packet pointer: in the next `refreshDisplay()` call, as it should be. Until then, the envir "won't trust" the state/contents of this field, so it shouldn't be a problem. Even from an educational perspective, it is important to show that these concerns (actual simulation, and "visualization") are somewhat separated.

The fact that the experimental Python bindings have a problem with this, is interesting indeed, but I guess you can work around it. (Maybe we could even annotate that function, so the returned pointer is treated as opaque? But will the equality check with the new, existing packet still work then?...)

**Comment by mmodenesi** [comment]
>  but I guess you can work around it

shure, not a problem!

Thanks again for your time.
