### ISSUE TITLE
INET ContentBasedClassifier never correctly matches the filters

### ISSUE THREAD

**Issue by Kathess** [omnetpp/omnetpp#831]
**Platform**
- OMNeT++ version: 5.6.1
- INET version: 4.2.0
- OS: Linux Mint 19.3

**Describe the bug**
The filter matching of the ContentBasedClassifier of INET does not work. Following the [official example for this module](https://inet.omnetpp.org/docs/tutorials/queueing/doc/ContentBasedClassifier.html), the classifier will always return the default gate and never correctly matches the filters to the content. No error, no warning, but all packets are forwarded to the first (the default) queue.

The error must be in "`filter->matches(packet)`" which never returns true in the function `int ContentBasedClassifier::classifyPacket(Packet *packet)` of the class _inet.queueing.classifier.ContentBasedClassifier.cc_

**To Reproduce**
To see the effect, the [example](https://inet.omnetpp.org/docs/tutorials/queueing/doc/ContentBasedClassifier.html) can just be rebuilt with the proposed .ini and .ned file. All packets are then forwarded to consumer1 (_defaultGateIndex_).

**Comment by levy** [comment]
Thanks for the bug report!

Unfortunately, you chose the wrong forum, because this is an INET bug and it should be filed at https://github.com/inet-framework/inet . I'll leave this open until the issue is resubmitted there.

I don't quite remember a related bug that was fixed since 4.2, but a lot has been changed since then. It actually works for me with the latest INET master branch. I have run the ContentBasedClassifier configuration from the queueing tutorial, and Consumer1 dropped 2 packets and consumer2 dropped 9 packets.

You may resubmit this issue on the INET github page if you feel like this is still a bug.
Please note that the latest INET master branch requires a not yet release OMNeT++ 6 version. Sorry for that, we're working on it.
