### ISSUE TITLE
Could you please update install guide hosted on omnetpp.org?

### ISSUE THREAD

**Issue by 0xSeanll** [omnetpp/omnetpp#839]
The [install guide](https://doc.omnetpp.org/omnetpp/InstallGuide.pdf) still only applies to macOS 10.12, and uses gdb as a debugger. Even the signing procedure is outdated for macOS 10.14 or later. I spent a lot of time today trying to get `gdb` to work on omnetpp which runs on my macOS 10.15. Just when I wanted to contribute the new signing method to the macOS install guide, I saw the source code for the installation guide has already been updated to macOS 10.15 and the debugger has changed to lldb `lldb`. So, why don't you just update it and save everyone's time?

**Comment by avarga** [comment]
The install guide you see online is for release 5.6.1. The install guide source you see in the repository's master branch is for the future 6.0 version where a number of things are done differently from 5.x, like lldb is used instead of gdb.

If you figured out the new signing procedure for macOS 10.14+, we'd be happy to include it in the install guide for the next 5.x release (version 5.6.3).

**Comment by 0xSeanll** [comment]
I found the new signing method on [gdb wiki](https://sourceware.org/gdb/wiki/PermissionsDarwin) (parts that marked with "Mac OS X 10.14 and later"). In addition to signing,  gdb binary is also required to be entitled.

**Comment by rhornig** [comment]
Thanks. If we ever happen to release a new version of OMNeT++ 5.6.x I've added this URL as a note to the install guide.
