### ISSUE TITLE
Export to csv problem using scavetool

### ISSUE THREAD

**Issue by spiroskatsampiris** [omnetpp/omnetpp#841]
**Platform**
 - OMNeT++ version: 5.3.3
 - OS: Windows 10

**Describe the bug**
When using "scavetool x *.sca -o measurements.csv" in order to expot to csv, this error occurs 
"scavetool: Assert: Condition 'bins.empty() || lowerBound > bins.back().lowerBound' does not hold in function 'addBin' at C:/Users/spiros/Documents/omnetpp-5.2.1-src-windows/omnetpp-5.2.1/src/common/histogram.h:58, file ML-sigma=0,networkSize=480m,adrMethod=avg,numberOfNodes=10-#0.sca, line 631"

**To Reproduce**
After running the simulation, try to export the results to csv format using "scavetool x *.sca -o measurements.csv"

**Comment by avarga** [comment]
Not enough information to reproduce. The bug report does not say which simulations were used to produce the said histograms. That info would be necessary to reproduce the issue, because in general, scavetool appears to work correctly on exporting histograms. (In the current codebase (6.0.3), running `opp_scavetool x *.sca */*.sca -o measurements.csv` in `samples/resultfiles` does not show this error.)  

Closing, as in 6.0 both the histogram collection class and the Scave library have been changed significantly, so it is possible that the bug no longer persists.
