### ISSUE TITLE
Error: Could not start user interface 'Qtenv' : MacOS

### ISSUE THREAD

**Issue by suheelsn** [omnetpp/omnetpp#842]
**Platform**
 - OMNeT++ version: [5.6.2]
 - OS: [MacOS Catalina 10.15.6]

**Describe the bug**
I have installed Omnet++ on my MacBook and trying to run my first simulation (tictoc example). I am getting below error while trying to run it with Omnet++ simulation.

```
OMNeT++ Discrete Event Simulation  (C) 1992-2019 Andras Varga, OpenSim Ltd.
Version: 5.6.2, build: 200518-aa79d0918f, edition: Academic Public License -- NOT FOR   COMMERCIAL USE
See the license for distribution terms and warranty disclaimer

User interface 'Qtenv' not found (not linked in or loaded dynamically).

Available ones are:
  Cmdenv : command-line user interface

<!> Error: Could not start user interface 'Qtenv'

End.
```

The simulation runs in command line but there is some issue with loading the GUI! Could this be something due to zsh shell in newer versions of mscOS? I have followed the instructions given in the installation guide in doc folder of the binaries. 
Can someone please help me resolve this and run the simulation in a GUI?

**Comment by rhornig** [comment]
I'm regularly using it with zshell. You should use 'source setenv' at the beginning (instead of . setenv), but other than that, you should be fine. To track this down, you should run ./configure and see whether the bundled QT libraries are correctly detected. The ./configure output should clearly indicate whether it was detected correctly. If not, check the config.log to see why it failed.

Most likely `setenv` was not sourced and that's why QT is not detected.
