### ISSUE TITLE
Plotting doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by screw** [omnetpp/omnetpp#857]
**Platform**
 - OMNeT++ version: 6pre9
 - OS: Ubuntu 20.04

**Describe the bug**
Double-click on any results data generates a plot but it does not contain any lines/data.
There is an X-axis and Y-axis with correct values, Title and legend wit correct label but there is no line (for line plot).

```
<home>/omnetpp/omnetpp-6.0pre9/ide/plugins/org.omnetpp.scave.pychart_6.0.0.201026-bef3cc9182/python/omnetpp/internal/backend_SWTAgg.py:62: MatplotlibDeprecationWarning: 
The _init_toolbar method was deprecated in Matplotlib 3.3 and will be removed two minor releases later. Please fully initialize the toolbar in your subclass' __init__; a fully empty _init_toolbar implementation may be kept for compatibility with earlier versions of Matplotlib.
  NavigationToolbar2.__init__(self, canvas)
```

**To Reproduce**
Run scenario, open results,  double click on a vector.

Is there a required package version for matplotlib, etc?

**Comment by torokati44** [comment]
The pasted error message is a notice of incompatibility with matplotlib >=3.3, that is already resolved internally.
But this in itself should not cause plotting to fail. None of the different kind of results, with any of the templates (from the context menu) produce anything useful?

**Comment by torokati44** [comment]
BTW, this is the commit that fixed the mentioned warning for us: https://github.com/omnetpp/omnetpp/commit/9c4611fe1ac9fd41feb44a88990187de43e06ffc

**Comment by screw** [comment]
Trying to plot scalar value (by double-click) produce only this text:
Please set the X Axis and Y Axis options in the dialog!

I found at least one vector that produces correctly looking plot, but the ones that I am interested in do not.
Both vectors have mean, min, max, etc in the browse Browse Data view

**Comment by torokati44** [comment]
Ah, that must be because you are getting a scatter chart.
You see, for each result type, the most recently used (compatible) template is used when simply double clicking.
So, the top one in the context menu, as they are ordered by time of last usage.
And a scatter chart cannot figure out the axes to use from just a single scalar. (In that case, we should probably just fall back to a bar chart, but there is not enough metadata about the templates yet for this...)

Is this most-recently-used template thing confusing?

**Comment by screw** [comment]
Ahaaaaa!
Now that I know how it works I can just right click and demand Bar chart right away.
I was just maniacally clicking around trying to see if any chart works.

Just make sure it is mentioned somewhere using UPPER CASE **BOLD** letters.

**Comment by torokati44** [comment]
This was traced back to two things:
 - The switch to the most recently used template when double-clicking (to scatter chart instead of bar chart, after once manually selecting it) was unexpected. It should be communicated more clearly somehow.
 - If the interpolationmode of a vector is none, there is indeed nothing drawn, because markers (symbols) are always disabled. In this case, they should be re-enabled.

**Comment by torokati44** [comment]
I think this is fixed by https://github.com/omnetpp/omnetpp/commit/d5e601dc06f9b29d91ea7c0daf6cb43f3b217d2d

**Comment by torokati44** [comment]
Closing this now with 6.0pre10 out.
If it still happens in the future, feel free to reopen, @screw!
