### ISSUE TITLE
DatarateChannel does not support infinite datarate

### ISSUE THREAD

**Issue by msvoelker** [omnetpp/omnetpp#860]
I was unable to configure a DatarateChannel with an infinite datarate (i.e. 0bps) with omnetpp-6.0pre10. If I configure a DatarateChannel with datarate=0bps and start the simulation, I get this error message.

> Cannot send packet ...: Unknown duration: No channel datarate, and no explicit duration supplied in the send call

I tried to use an IdealChannel or DelayChannel instead. If I use one of these channels and start the simulation, I get this error message.

> getTransmissionChannel(): No transmission channel found in the connection path between gates ...

Here is my setup.

```
import inet.networklayer.configurator.ipv4.Ipv4NetworkConfigurator;
import inet.node.inet.Router;
import inet.node.inet.StandardHost;

network Simple
{
    types:
//        channel idealLink extends ned.IdealChannel {}
        channel idealLink extends ned.DatarateChannel
        {
            datarate = 0bps;
            delay = 0ms;
            per = 0;
        }
//        channel bottleneckLink extends ned.DelayChannel {
//        	delay = 10ms;
//        }
        channel bottleneckLink extends ned.DatarateChannel
        {
            datarate = 0bps;
            delay = 10ms;
            per = 0;
        }
    submodules:
        configurator: Ipv4NetworkConfigurator {
            parameters:
                @display("p=222,32");
        }
        
        router1: Router {
            parameters:
                @display("p=146,137");
        }

        router2: Router {
            parameters:
                @display("p=305,137");
        }

        sender: StandardHost {
            parameters:
                @display("p=57,137");
        }

        receiver: StandardHost {
            parameters:
                @display("p=390,137");
        }

    connections:
        sender.pppg++ <--> idealLink <--> router1.pppg++;

        router1.pppg++ <--> bottleneckLink <--> router2.pppg++;

        router2.pppg++ <--> idealLink <--> receiver.pppg++;
}
```

Is there a way to use a channel with infinite datarate?

I found in src/sim/cdataratechannel.cc the line that gave me the Unknown duration error.

https://github.com/omnetpp/omnetpp/blob/8f4b83553716dca653c93b1f83f49bdd2b5154ba/src/sim/cdataratechannel.cc#L254

Replacing this line with `duration = 0;` fixed my issue.

**Comment by rhornig** [comment]
There is a reason why infinite data rate is not allowed when you are sending `cPackets` with length. OMNET can deliver events to your model at both the start and the end of the packet transmission and any sane code would assume that start event is delivered **before** the **end**. If you allow infinite data rate, start and end event would heppen at the same time and the order between them became indeterminate. That could cause serious issues with the code. The simulator assumes that if you specified a packet length in bytes, you specified it because you expect it to be transmitted in more that 0 seconds (otherwise you could specify 0 for the packet length (or use cMessages and DelayChannel instead).

INET modells real life protocols and transmission speed between nodes can never be 0.

That's being said, nothing stops you to specify arbitrary large values for transmission speed. Anything less INFINITE is a fair game as it does not cause the above problems.

**Comment by a-andre** [comment]
Best way to solve this would be to make the example work with `IdealChannel` instead.

Any idea or suggestions how to fix 
> getTransmissionChannel(): No transmission channel found in the connection path between gates

mentioned by @msvoelker.

**Comment by rhornig** [comment]
You cannot use IdealChannel between hosts in INET because the protocols also assume that the transmission of a packet takes a non 0 time. The only way around this is to specify an extremely large transmission speed for the network links.
