### ISSUE TITLE
Calling the random number generator changes the simulation trajectory so should not be const

### ISSUE THREAD

**Issue by edlongman** [omnetpp/omnetpp#870]
All the random number generation functions are `const`. However calling them can have non-const effects since it changes the results of future calls.
https://github.com/omnetpp/omnetpp/blob/fd156622389bf93c889b819248ef929a45ad1eca/include/omnetpp/ccomponent.h#L526

I appreciate this probably would break a huge number of other dependant const functions but I stuggle to see why gcc even allows this to compile in the first place.

**Comment by torokati44** [comment]
The `const`-ness of a member function only forbids modifying (non-`mutable`) members of the object itself on which it is called.
It says nothing about other objects referenced by (unmodified!) pointer members.
There's nothing wrong with this according to any compiler: https://godbolt.org/z/hq1oEW

The "changes the simulation trajectory so should not be const" logic is not necessarily a valid point, as the `const`-ness of something is mostly a technicality of C++ as a language, rather than something that should have such overarching effects on the entire design of a software of this complexity.

**Comment by edlongman** [comment]
Ok, thanks for pointing that out, I thought that it was not allowed to change any referenced objects either but clearly that is allowed!
