### ISSUE TITLE
Error Message: The OMNET++ IDE is not installed

### ISSUE THREAD

**Issue by vishav26** [omnetpp/omnetpp#888]
**Platform**
 - OMNeT++ version: 5.6.2
 - OS: Ubuntu18.04

**Describe the bug**
I am getting started with Omnet++. I cloned the repository and switched to the tag 5.6.2. I created a configure.user file, configure the Omnet and make the project. The make was successful but when I try to launch OMNET, I get an error "The OMNET++ IDE is not installed" 

**To Reproduce**
1. Clone the repository
2. Copy configure.user.dist to configure.user
3. ./configure
4. make
5. omnetpp 
6. Error: The OMNet++ IDE is not installed

**Comment by vishav26** [comment]
@avarga 

Hey. I feel something is missing in repository. It does not install the ide.

**Comment by buraksenkus** [comment]
Same for me in Ubuntu 21.04.

**Comment by buraksenkus** [comment]
When we download the Linux version from Omnet's download page, there is a folder named **ide**, but when cloned via GitHub, this folder does not exist. Is it not possible to run the IDE from cloned source code?

**Comment by edlongman** [comment]
The IDE is not part of this repo because it is mainly the eclipse project. 

Instead you can just download and extract the download. If you want to change the omnet version using git you can copy the contents of the download into your cloned repo and then it will work (after ./configure and make)

**Comment by avarga** [comment]
The IDE sources are in the the repo actually, in the [ui/](https://github.com/omnetpp/omnetpp/tree/master/ui) directory. It's just not so easy to build a standalone IDE from the sources.

However, if you want to give it a try, there is a recipe for building a full OMNeT++ distro using docker on our [docs server](https://docs.omnetpp.org/articles/building-omnetpp-in-docker/). You can copy the IDE out of the resulting archive.

**Comment by adi-g15** [comment]
> Instead you can just download and extract the download. If you want to change the omnet version using git you can copy the contents of the download into your cloned repo and then it will work (after ./configure and make)

I think, there should be a note in README for this. Since, **many websites link to Github releases page** for downloading specific versions of OMNET++ (eg. INET, Veins, Simu), where the person won't have the `ide/` directory, and hence unable to run omnet.

Also, the solution to just download from omnet++ website also causes incompatible version, for eg. [Simu5G](https://github.com/Unipisa/Simu5G) requires 6.0-pre10, and won't even build under 6.0 or 5.7, the available versions on omnet++ website.

The users will still face problems, since the releases don't have it in their copy of README. But maybe they find a solution by reading the README at this github repo.

If ok, I can create a PR for this :)

**Comment by rhornig** [comment]
The release pages on github actually contain all the downloadable versions for different operating systems, so it is quite ok to point there. (the release page also adds links automatically to the repo snapshots, but they are clearly labelled as "Source code", so the user is expected to do the full build, including the build of IDE.)

In fact, you can build the IDE easily as long as you have docker installed. Just type: `make ide`
