### ISSUE TITLE
Correct install commands for linux distros

### ISSUE THREAD

**Issue by Isaac-DeFrain** [omnetpp/omnetpp#954]
**Platform**
 - OMNeT++ version: 6.0.1
 - OS: Debian 10 (but it isn't important)

**Describe the bug**
The install guide (pg. 18) says to do `source setenv` (this only applies if we put `setenv` on our path)
![image](https://user-images.githubusercontent.com/42081488/201484909-e057e1ff-46c5-4e28-8152-85ac7905681b.png)

Please add one sentence saying if you *don't* put `setenv` on your path, then you can do `source ./setenv` instead. I know, it's totally obvious, but it will prevent people unnecessary headache.

**To Reproduce**
Clone the repo and do
```
cd omnetpp
source setenv
./configure
```
It doesn't work... unless you put `setenv` on your path.

**Comment by Isaac-DeFrain** [comment]
I ran into several dependency issues after correcting this one. Why isn't there a included script to get all dependencies and add necessary items to path?

I ended up abandoning the debian install for windows. I must say, this is first instance of software I've found that is easier to work with on windows.

**Comment by avarga** [comment]
You wrote: *"Clone the repo and do..."*.  That is wrong. The Installation Guide documents the way to install from the released tarball, not by cloning the git repo as you presumably did. Cloning the repo and building from there is normally only done by the OMNeT++ developer team, and it needs additional setup not documented in the Install Guide.

*"Why isn't there a included script to get all dependencies and add necessary items to path?"*

Because the process of installing additional software is highly OS and distro dependent.

**Comment by avarga** [comment]
Closing for lack of any actionable item. Please reopen if you have some specific issue to report.

**Comment by Isaac-DeFrain** [comment]
"The Installation Guide documents the way to install from the released tarball, not by cloning the git repo as you presumably did."

You're right that's exactly what I did! Thank you for clarifying. I'll try to install again using the tarball this time.
