### ISSUE TITLE
ELOG sequence chart: NED type filter removing too many messages

### ISSUE THREAD

**Issue by cguerber** [omnetpp/omnetpp#968]
**Platform**
 - OMNeT++ version: 6.0.1
 - OS: Debian 11

**Describe the bug**
The simulation contains 5 identical "host" nodes plus a ground station. We do not use INET.
Transmissions are modeled in the code by duplicating (dup method) the initial message and send the copies them to all the nodes, so all the messages shall have the exact same characteristics.
In the sequence chart view of the ELOG file resulting from the simulation, the default display is all fine: all the messages are displayed. We need to remove some of these for pedagogical reasons. If we apply a NED type filter, some of the messages are erroneously removed, especially, the events corresponding to these messages are still present. The same action worked well on OMNeT++ 4.6.

**To Reproduce**
Open provided elog file in the sequence chart viewer (we removed unnecessary events from the original elog file)
[example_short.elog.zip](https://github.com/omnetpp/omnetpp/files/11222543/example_short.elog.zip)
. All the messages are present. Right click, Filter -> Filter..., select NED type and select vdl_mode2.datalink.mac.CSMA, click OK.
We expect 5 messages being sent from the transmitting node to every other nodes, but we get only 2 of them. Whatever the node that is transmitting during the simulation, the chart shows 2 messages are going to the same nodes (here ac[3] and ac[4]), except of course if the transmission comes from one of these two. In that case, still 2 messages, one goes to the other one as usual, the second goes to a third one (here ac[1]), always the same (first and last transmission in the example).

**Comment by levy** [comment]
When the sequence chart displays a filtered event log file, it tracks the cause/consequence relationship for each event individually. This process is time consuming and it can produce a large number of arrows depending on how far the sequence chart looks back/forward in the event log. There are limits to how far the sequence chart looks back/forward and how many arrows it collects. You can set these limits in the filter dialog by selecting the 'Collection limits' item on the left. The maximum number of message dependencies per event is limited to 5 by default. If you increase this limit to 10 you will see the five arrows that you are looking for. The value that needs to be set in order to see all 5 arrows seems to be doubled, but there are 5 additional arrows which are hidden by default. You can enable those arrows from the Show/Hide menu using the 'Show Message Dependencies' menu item.

**Comment by cguerber** [comment]
Works well. Thanks for the explanation.
